name: cpp_check
on: [push]
jobs:
  cpp-check:
    name: Run static analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Git and cppcheck env
        run: |
          sudo apt install -y git
          sudo apt install -y gcc
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Job's status is ${{ job.status }}."
