name: cpp_check
on: [push, pull_request]
jobs:
  cpp-check:
    name: Run static analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Git and cppcheck env
        run: |
          sudo apt install -y git
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run cpp-check
        run: |
          /bin/bash ./tests/cpp_check.sh
      - run: echo "Job's status is ${{ job.status }}."
